language: java
script: gradle dist
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: H6IQkWgTwIPSyjNOorF1QKHQqXd+zrGtUrWTSPNxNQi1ImLZsIxTZgDF+21/nSP60IswriUT9FsEA65gilm4FpOfYBdJVzdMs+dRf+t7K2oHc1rHqQB35CkrnG1mjoCtLqVL3GW9fFmV9Z927CUoUrUyq8pPZsw6+FcKwgWS1HMwUQwu2WBPMRmX0ZUZQdLNY26xmKgb+3VFhrIepntXSbGP8fjHM3nTctuapBhQxc0AtbXNxG4vKcEkrCOt0g7MEwzjlcMxs+h5y6LPckMyHIy08LhMKuVj59DQdqUL4ph6Kg7V9DR7mgF+pSYfY4tUU/hk7RMbKDT6AxH72sxBPKl5bVlMBli9PzsnSSv4UlAiyZlzR/zCWO2pv8vls41jtpDDjnpfR80vTyduDfFb6kmx1PgMEXEsYh+XrxA9G74yrvnf5nKO18mSJJQXmxVtG5U3Mia/PZ3DcId7DH8qEREmXFc45IASix8C32ukozhAmVdBnwlEoZOysywtGs+jclo1Jlx1Czlw0JuAej8zF2FRcA2Cgx7t8gzmnXJSX3YhPFCgnn8skAhLxW1/w23/Ox12ZS1TZ08HsfCrq8Rp+Uxe+PvR46hRTv2qdCUmSBwpxoazqeqHSwvcnjyVVp3Kbg19snbbhhznlVwdSIB4r/dgNA/gU1MkVTC8d4PRnss=
  file:
    - build/distributions/xmlcalabash1-pegdown-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
