language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: PJAAHamzU258vRMnnw92ydlAtbLgHH9v3e43vI9o0n57F2DNkw5BLgDLQU/5bXsXmrcp7B6O9zLvTeQRjYcviKdiiS+BKjl7qAnUeSEgFX7duZxMROlLRbdboz6eQROA1hHZx1DemUty0vQ7GubHK6QjeRscPf3OjZV53WOWU2qokXgKVGaajaBcifXWAQ4Jd7Rtn6zMdKpcd6S/sPF2Yg8gXwqThIJz17/hG53C3PNoFaptTM6EX0f5HrmICQZzkClqUoIk8Awc3VuSl8NgHDTTxxb2QHyJjAaW14TTA+ZkesB2kMtn27M7k+nB5yWG/Z98p1j74bd/RmUg3oCYNNffLeG+VJRQKzzeFDnMYqfd9Yis9trrY5OzGNsRfMeaB/C1cAxhKvGfLl+FTZ4UHvDYoo2vfIuTjdzGr3Iu1tdP0nc7ZqOl00oZJmi3Aqm8SwpoShLSFcwRP89dts5GrBIz2mJiD7EdrRnz3Nr+7cu2UksbNnYNluQC4BthwkdfQT/R9ka2/0xOrjXW5BTCmg3k1M8sZ40oA3vTmyCy3dWl55CoCUg323urvM+VED9tD2GatDznx91pp/aeyHbz08iAB2guxlt1f1Hm4BL1+pXmvqIEfV5UuCowIu6JZiKB8stGoTuWI6oxccc+cTLEJckkKjD17JSxiEc5TtCYX0s=
  file:
    - build/distributions/xmlcalabash1-pegdown-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
